# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.restdataexport.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - name: rdeserverport
      port: {{ .Values.config.restdataexport.int.rdeserverport }}
      targetPort: {{ .Values.config.restdataexport.int.rdeserverport }}
      nodePort: {{ .Values.config.restdataexport.ext.rdeserverport }}
  selector:
    app: restdataexport
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restdataexport
  name: deployment-rest-export
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: restdataexport
  template:
    metadata:
      labels:
        app: restdataexport
    spec:
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
      - name: ia-rest-export
        image: {{ .Values.DOCKER_REGISTRY }}openedgeinsights/ia_rest_export:{{ .Values.EII_VERSION }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          privileged: true
        volumeMounts:
        {{- if eq .Values.config.restdataexport.IPC true}}
        - name: {{ .Values.volumes.eii_socket.name }}
          mountPath: {{ .Values.volumes.eii_socket.location }}
        {{- end }}
        - name: tmp-ssl
          mountPath: "{{.Values.env.EII_INSTALL_PATH }}/rde"
        {{ if eq .Values.env.DEV_MODE false}}
        - name: etcd-certs
          mountPath: /run/secrets/etcd/
        {{ end }}

        env:
        - name: AppName
          value: "RestDataExport"
        - name: DEV_MODE
          value: '{{ .Values.env.DEV_MODE }}'
        - name: HTTP_METHOD_FETCH_METADATA
          value: '{{ .Values.env.HTTP_METHOD_FETCH_METADATA }}'
        - name: ETCD_HOST
          value: {{ .Values.config.etcd.name }}
        - name: ETCD_CLIENT_PORT
          value: '{{ .Values.config.etcd.client_port }}'
        - name:  ETCD_PREFIX
          value: ''
        {{- if eq .Values.config.restdataexport.IPC false}}
        {{- if .Values.config.video_analytics }}
        - name: SUBSCRIBER_default_ENDPOINT
          value: "{{ .Values.config.video_analytics.name }}:{{ .Values.config.video_analytics.publish_port }}"
        - name: SUBSCRIBER_default_TYPE
          value: "zmq_tcp"
        {{- end }}
        {{- if .Values.config.influxdbconnector }}
        - name: SUBSCRIBER_influxSub_ENDPOINT
          value: "{{ .Values.config.influxdbconnector.name }}:{{ .Values.config.influxdbconnector.point_classifier_data_port }}"
        - name: SUBSCRIBER_influxSub_TYPE
          value: "zmq_tcp"
        {{- end }}
        {{- if .Values.config.imagestore }}
        - name: CLIENT_ImageStore_ENDPOINT
          value: "{{ .Values.config.imagestore.name }}:{{ .Values.config.imagestore.server_port }}"
        - name: CLIENT_ImageStore_TYPE
          value: "zmq_tcp"
        {{- end }}
        {{- else }}
        - name: SUBSCRIBER_default_ENDPOINT
          value: "{{ .Values.env.SOCKET_DIR }}"
        - name: SUBSCRIBER_default_TYPE
          value: "zmq_ipc"
        - name: SUBSCRIBER_influxSub_ENDPOINT
          value: "{{ .Values.env.SOCKET_DIR }}"
        - name: SUBSCRIBER_influxSub_TYPE
          value: "zmq_ipc"
        - name: CLIENT_ImageStore_ENDPOINT
          value: "{{ .Values.env.SOCKET_DIR }}"
        - name: CLIENT_ImageStore_TYPE
          value: "zmq_ipc"
        {{- end }}
        {{ if eq .Values.env.DEV_MODE false}}
        - name: CONFIGMGR_CACERT
          value: "/run/secrets/etcd/cacert.pem"
        - name: CONFIGMGR_CERT
          value: "/run/secrets/etcd/RestDataExport_client_certificate.pem"
        - name: CONFIGMGR_KEY
          value: "/run/secrets/etcd/RestDataExport_client_key.pem"
        {{ end }}

      volumes:
      {{- if eq .Values.config.restdataexport.IPC true}}
      - name: {{ .Values.volumes.eii_socket.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.eii_socket.name }}
      {{- end }}
      - name: tmp-ssl
        emptyDir:
          medium: Memory
      {{ if eq .Values.env.DEV_MODE false}}
      - name: etcd-certs
        secret:
          secretName: eii-certs
          items:
          - key: cacert.pem
            path: cacert.pem
          - key: RestDataExport_client_certificate.pem
            path: RestDataExport_client_certificate.pem
          - key: RestDataExport_client_key.pem
            path: RestDataExport_client_key.pem
      {{ end }}
